sudo: required

env:
  global:
    - IMAGE_NAME=bywater/koha-ncip-server
    - REGISTRY_USER=kylemhall
    # REGISTRY_PASS=...
    - secret: "dsfkjdf78ewr23rju32j323288ewuiwf87dsfhjser87sef87dsfiudsfhj"

jobs:
  include:
    - stage: run integration tests
      services:
        - docker

      script:
        - cd docker
        - ./test_integration.sh -v master

    - stage: build docker image
      services:
        - docker

      before_script:
        - version="$TRAVIS_COMMIT"
        - docker pull "$IMAGE_NAME" || true

      script:
        - docker build --pull -f docker/Dockerfile --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

      after_script:
        - echo "VERSION ${version}"
        - docker images

      before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:master-latest"

      deploy:
        provider: script
        script: docker push "${IMAGE_NAME}:master-latest"
        on:
          tags: false
          all_branches: true
