sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=bywater/koha-ncip-server
    - REGISTRY_USER=kylemhall
    # REGISTRY_PASS=...
    - secret: "dsfkjdf78ewr23rju32j323288ewuiwf87dsfhjser87sef87dsfiudsfhj"

before_script:
  - version="$TRAVIS_COMMIT"
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull -f docker/Dockerfile --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - echo "VERSION ${version}"
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
