name: CI
on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  schedule:
    - cron: "0 6 * * *"
jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run integration tests
      run: |
        cd docker
        ./test_integration.sh -v master
